### ISSUE TITLE
Can't switch auto paste mode in vim after 2.4 version

### ISSUE THREAD

**Issue by yutakatay** [tmux/tmux#968]
I'm using vim with tmux. I switch to paste mode automatically when pasted from the clipboard. I got it until tmux version 2.3, but now I can not do it.
According to my examination, I think that there is a problem from 743f772bef538b8974ea0b331104f3ca00c89c70 .

### environments:
Linux x86_64
tmux 2.5
screen-256color
command: tmux -vv -Ltest -f/dev/null new

### expect
```yml
language: c
matrix:
    include:
        - compiler: gcc
        - compiler: clang
          env: CFLAGS="-g -O2"
```

### actual
```yml
language: c                                                                                                                                                                                                                      
matrix:                                                                                                                                                                                                                          
      include:                                                                                                                                                                                                                   
                - compiler: gcc                                                                                                                                                                                                  
                          - compiler: clang                                                                                                                                                                                      
                                      env: CFLAGS="-g -O2"     
```

my .vimrc for auto paste
```vim
if &term =~? 'xterm' || &term =~? 'screen'
  function! WrapForTmux(s)
    if !exists('$TMUX')
      return a:s
    endif

    let tmux_start = "\<Esc>Ptmux;"
    let tmux_end = "\<Esc>\\"

    return tmux_start . substitute(a:s, "\<Esc>", "\<Esc>\<Esc>", 'g') . tmux_end
  endfunction

  let &t_SI .= WrapForTmux("\<Esc>[?2004h")
  let &t_EI .= WrapForTmux("\<Esc>[?2004l")

  function! XTermPasteBegin(ret)
    set pastetoggle=<Esc>[201~
    set paste
    return a:ret
  endfunction

  inoremap <special> <expr> <Esc>[200~ XTermPasteBegin("<C-g>u")
endif
```
